### ISSUE TITLE
Development branch aanmaken (optioneel)

### ISSUE THREAD

**Issue by Revin400** [Revin400/Software-construction-process-and-tools#14]
Context: 
Een aparte development branch kan helpen bij het vermijden van merge-conflicten in de hoofdtak en biedt een veilige ruimte voor onafgemaakte features. Dit was een aanbeveling van de Product Owner.

Actie: 
Maak een development branch en spreek met het team af hoe en wanneer deze wordt gebruikt.

**Comment by JaySurj** [comment]
Ya the thing is done

**Comment by JaySurj** [comment]
its works dont push the data to main aka production
